# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeBell < Formula
  desc "Notification sounds for Claude Code"
  homepage "https://github.com/Tiimie1/claude-bell"
  version "0.3.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/Tiimie1/claude-bell/releases/download/v0.3.1/claude-bell_darwin_amd64.tar.gz"
    sha256 "d94770518bb86317f31705709cb475b1c63dab351233096ebd275a6abf71a3a2"

    def install
      bin.install "claude-bell"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/Tiimie1/claude-bell/releases/download/v0.3.1/claude-bell_darwin_arm64.tar.gz"
    sha256 "d29abe5cfe8c16bbb9823cc4e48051e694964461abc9973ab75866a9d46d2f84"

    def install
      bin.install "claude-bell"
    end
  end
end
