# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeBell < Formula
  desc "Notification sounds for Claude Code"
  homepage "https://github.com/Tiimie1/claude-bell"
  version "0.2.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/Tiimie1/claude-bell/releases/download/v0.2.1/claude-bell_darwin_amd64.tar.gz"
    sha256 "bd3a24a8ad56ec36e95c8ef358b62caec88aeb752e8cfadce35cb888b025c122"

    def install
      bin.install "claude-bell"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/Tiimie1/claude-bell/releases/download/v0.2.1/claude-bell_darwin_arm64.tar.gz"
    sha256 "8702234f8c01ae4152219622e853206a1a2bc45fe3603c626e1dd48940d0d1c9"

    def install
      bin.install "claude-bell"
    end
  end
end
